---
title: "BostonHousing"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{BostonHousing}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
Attach libraries:
```{r setup}
library(BonusLab)
library(dplyr)
library(mlbench)
library(caret)
library(MASS)
```
Load and preview the dataset:
```{r}
data(BostonHousing)
dim(BostonHousing)
head(BostonHousing)
```
Divide the dataset into training and test set:
```{r}
set.seed(42)
inTrain <- caret::createDataPartition(y = BostonHousing$medv, p = .75,
                                      list = FALSE)

training <- BostonHousing[ inTrain,]
testing <- BostonHousing[-inTrain,]
nrow(training)
nrow(testing)
```
Fit a linear model, and a linear model with forward selection on the training set using the caret package:
```{r}
lm_train <- train(medv ~ .,data = training,method = 'lm')

grid <- data.frame(c(1,2,3))
names(grid) <- c("nvmax")
lmFit <- train(medv ~ .,data = df_test,intercept=TRUE,
               method = 'leapForward',tuneGrid=grid)
```

